# Site settings | 网站设置
# _config.alog.yml
logo: logo 路径

menu:
  - name: Home
    path: /
  - name: Projects
    path: /projects
  - name: Message
    path: /message
  - name: Links
    path: /links
  - name: About
    path: /about

links:
  site_info:
    name: Alog
    link: https://akino.icu
    icon: https://akino.icu/images/avatar.jpg
  apply_tips: Apply format:\nName：xxxx\ndesc:xxx\nLink：xxx\nIcon：xxx
  link_list:
    - name: Akino
      avatar: /images/avatar.jpg
      link: https://akino.icu
      desc: Akino's blog.

# v1.1.0
page_header: 
  type: letter # 模板文件名
  platforms: # 自定义的page header将在哪些设备端上展示，不展示自定义header的设备端将使用默认的page header
   - pc
   - mobile
  apply_pages: # 应用到哪些页面(布局)
    - message
  title: Message # 可选配置项，根据自己需求
  content:
    - First line
    - Second line
    - ...

footer:
  enable: true
  building_time: 2023 # 建站时间

# 开启页面加载动画
loading:
  enable: true

# 开启文章阅读次数统计
busuanzi:
  enable: true

comment:
  use: valine # valine | waline | twikoo
  valine: # 配置详见valine官方文档: https://valine.js.org/
    appId: your app id
    appKey: your app key
    avatar: avatar style
    placeholder:  xxx # 评论输入框占位文字
    pageSize: 10 # 评论列表每一页的评论数量
    visitor: true # 文章阅读次数统计
    recordIP: true
  waline: # 配置详见waline官方文档: https://waline.js.org/
    serverURL: # 部署 url
  twikoo: # 配置详见twikoo官方文档: https://twikoo.js.org/
    envId: # 腾讯云填 env id，Vercel填部署的 server url
    region: ap-shanghai # default: ap-shanghai

# 本地搜索依赖hexo-generator-searchdb，在使用前请先安装该依赖
local_search:
  enable: true
  top_n_per_article: 1 # 每篇文章显示的搜索匹配数量
  preload: true # 预加载数据
  trigger: auto